### ISSUE TITLE
Request for full code

### ISSUE THREAD

**Issue by Oceandeepzxr** [xychen2022/3DFasterRCNN#3]
Hi, there! 
Nice work! I'm working on landmark detection on 3D CT image, and your work really helps me a lot. However, I found only coarse stage code here, could you plz provide the full code? my email: gavinzhao1997@163.com.
Many thanks! :D

**Comment by xychen2022** [comment]
Hi,

Glad to know you found our work useful! I have pushed the phase 2 code to the GitHub repo. You can find it in the folder named Phase2_code. 

As mentioned in ReadMe, the code I just shared is not tested due to multiple reasons. You may encounter errors when using it. Let me know if you find an error and your solution to it.

Thanks

**Comment by Oceandeepzxr** [comment]
Thanks!
