### ISSUE TITLE
Problems with Training

### ISSUE THREAD

**Issue by Oceandeepzxr** [xychen2022/3DFasterRCNN#4]
Hi, I got a problem when I start training, here is the error message:
<img width="829" alt="image" src="https://github.com/xychen2022/3DFasterRCNN/assets/42764972/6e44f84b-6df8-446d-a872-b3d754ee9e60">
Im using Python3.8, tensorflow2.5 with cuda 11.8(Changing the version doesnt seem possible  since im using a public server). Could you tell me how this error message may come from?

**Comment by xychen2022** [comment]
It is difficult to identify the problem without you providing more information. Have you changed the default setting and/or the data? 

Anyway, you can try on the provided data first and this will familiarize yourself with our algorithm.

**Comment by Oceandeepzxr** [comment]
Thanks for the reply, Im using provided data, here is full log for running training code 'python landmark_detection_group1_size24.py':
<img width="818" alt="未命名图片" src="https://github.com/xychen2022/3DFasterRCNN/assets/42764972/3218313a-1726-481d-b6cd-a03f67a0b575">
<img width="829" alt="未命名图片1" src="https://github.com/xychen2022/3DFasterRCNN/assets/42764972/27b4d64b-3d7d-4cb7-bece-ec9eeb3eb1b8">
<img width="826" alt="未命名图片2" src="https://github.com/xychen2022/3DFasterRCNN/assets/42764972/db066448-7259-4285-9a0c-fcb9e908838d">
please tell me if something Im missing, thanks in advance.

**Comment by xychen2022** [comment]
The second screenshot has told you the problem. Since your environment is different than ours (Tensorflow 2.5, CUDA 11.2 and cuDNN 8.1), you need to compile the two CUDA C codes, 3D ROI-align and non-maximum suppression, before using the algorithm, which is already mentioned in ReadMe. To compile the sources codes, please follow the instructions given in the ReadMe under folders CropAndResize3D and non_max_suppression. Then, change the paths in landmark_detection_group1_size24.py or replace crop_and_resize_op_gpu.so and non_max_suppression_op.so in the current folder with the ones you got after recompiling.

**Comment by Oceandeepzxr** [comment]
Thanks! Im working on it, I'll let you know if theres any problem 👍 :D

**Comment by CarrieX6** [comment]
@xychen2022 Hi, I'm having the same issue. I'm still getting the same bug after recompiling two C files. Could you tell me how it was resolved? Thanks a lot!
![image](https://github.com/xychen2022/3DFasterRCNN/assets/38813464/23301bcc-e7dd-4b4d-bc55-e26cde1d0522)
![image](https://github.com/xychen2022/3DFasterRCNN/assets/38813464/622d0ccc-7fdc-433a-a902-c65d339108f0)
